import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import routesRouter from "./routes";
import busesRouter from "./buses";
import driversRouter from "./drivers";
import tripsRouter from "./trips";
import bookingsRouter from "./bookings";
import walletRouter from "./wallet";
import promoRouter from "./promo";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import driverRouter from "./driver";
import supportRouter from "./support";
import suggestionsRouter from "./suggestions";
import driverDocumentsRouter from "./driverDocuments";
import staffRouter from "./staff";
import dashboardRouter from "./dashboard";
import ridesRouter from "./rides";
import zonesRouter from "./zones";
import zonePricingRouter from "./zonePricing";
import shuttleRouter from "./shuttle";
import earningsRouter from "./earnings";
import vehiclesRouter from "./vehicles";
import auditLogsRouter from "./auditLogs";
import locationsRouter from "./locations";
import paymentsRouter from "./payments";
import ratingsRouter from "./ratings";
import chatRouter from "./chat";
import serviceControlsRouter from "./serviceControls";
import checkinRouter from "./checkin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(routesRouter);
router.use(busesRouter);
router.use(driversRouter);
router.use(tripsRouter);
router.use(bookingsRouter);
router.use(walletRouter);
router.use(promoRouter);
router.use(notificationsRouter);
router.use(adminRouter);
router.use(driverRouter);
router.use(supportRouter);
router.use(suggestionsRouter);
router.use(driverDocumentsRouter);
router.use(staffRouter);
router.use(dashboardRouter);
router.use(ridesRouter);
router.use(zonesRouter);
router.use(zonePricingRouter);
router.use(shuttleRouter);
router.use(earningsRouter);
router.use(vehiclesRouter);
router.use(auditLogsRouter);
router.use(locationsRouter);
router.use(paymentsRouter);
router.use(ratingsRouter);
router.use(chatRouter);
router.use(serviceControlsRouter);
router.use(checkinRouter);

export default router;
